import type { Metadata } from "next";
import "./globals.css";

import HeaderMenu from "@/components/header-components/header-menu";
import Footer from "@/components/home-components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderMenu />

        {children}
        <Footer />
      </body>
    </html>
  );
}
